AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  waf-auto-gen
  Sample SAM Template for test-waf-auto-gen
Resources:
  StockTradingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionSubstitutions:
        BedRockWAFGenFunctionArn: !GetAtt BedRockWAFGenFunctionArn.Arn
        SESFunctionArn: !GetAtt SESFunction.Arn
        ApplyWAFArn: !GetAtt ApplyWAF.Arn
        WAFFixArn: !GetAtt WAFFix.Arn
        BedrockFilterArn: !GetAtt BedrockFilter.Arn
      Events:
        HourlyTradingSchedule:
          Type: Schedule
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: false
            Schedule: rate(1 hour)
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref BedRockWAFGenFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref SESFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ApplyWAF
        - LambdaInvokePolicy:
            FunctionName: !Ref WAFFix
        - LambdaInvokePolicy:
            FunctionName: !Ref BedrockFilter
      DefinitionUri: statemachine/waf_gen.asl.json
  BedRockWAFGenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/bedrock_waf_generate/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
  SESFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/SES/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
  ApplyWAF:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Apply_WAF/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
  WAFFix:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/bedrock_waf_fix/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
  BedrockFilter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/bedrock_cve_filter/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
Outputs:
  StockTradingStateMachineArn:
    Description: Stock Trading State machine ARN
    Value: !Ref StockTradingStateMachine
  StockTradingStateMachineRoleArn:
    Description: IAM Role created for Stock Trading State machine based on the specified SAM Policy Templates
    Value: !GetAtt StockTradingStateMachineRole.Arn